"""update relationship

Revision ID: 205ab30311e3
Revises: d4eb0b4aa934
Create Date: 2023-05-29 11:37:50.644928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205ab30311e3'
down_revision = 'd4eb0b4aa934'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
