"""update repr for Reservation

Revision ID: 69bdc3d72b4f
Revises: 205ab30311e3
Create Date: 2023-06-02 10:29:11.542735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bdc3d72b4f'
down_revision = '205ab30311e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
