"""create planes and passengers and relationships

Revision ID: 8c4c614c3c84
Revises: 3e2f8a6ef876
Create Date: 2023-05-29 10:28:58.749433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4c614c3c84'
down_revision = '3e2f8a6ef876'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plane_type', sa.String(), nullable=True),
    sa.Column('passenger_limit', sa.Integer(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], name=op.f('fk_planes_flight_id_flights')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(), nullable=True),
    sa.Column('passenger_age', sa.Integer(), nullable=True),
    sa.Column('plane_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plane_id'], ['planes.id'], name=op.f('fk_passengers_plane_id_planes')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passengers')
    op.drop_table('planes')
    # ### end Alembic commands ###
