"""add flights table

Revision ID: bf0978ebad32
Revises: df114287ba22
Create Date: 2023-05-29 11:01:16.105548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0978ebad32'
down_revision = 'df114287ba22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_city', sa.String(), nullable=True),
    sa.Column('arrival_city', sa.String(), nullable=True),
    sa.Column('plane_type', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    # ### end Alembic commands ###
