"""delete all tables

Revision ID: df114287ba22
Revises: 8c4c614c3c84
Create Date: 2023-05-29 10:58:56.980317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df114287ba22'
down_revision = '8c4c614c3c84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passengers')
    op.drop_table('planes')
    op.drop_table('flights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('departure_city', sa.VARCHAR(), nullable=True),
    sa.Column('arrival_city', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plane_type', sa.VARCHAR(), nullable=True),
    sa.Column('passenger_limit', sa.INTEGER(), nullable=True),
    sa.Column('flight_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], name='fk_planes_flight_id_flights'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passengers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('passenger_name', sa.VARCHAR(), nullable=True),
    sa.Column('passenger_age', sa.INTEGER(), nullable=True),
    sa.Column('plane_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['plane_id'], ['planes.id'], name='fk_passengers_plane_id_planes'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
