"""change base

Revision ID: f4f7b7961797
Revises: 69bdc3d72b4f
Create Date: 2023-06-02 10:33:54.389511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f7b7961797'
down_revision = '69bdc3d72b4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
